### ISSUE TITLE
Why not merge this C binding with the other bindings in the pymavlink repo?

### ISSUE THREAD

**Issue by davidbuzz** [olliw42/fastmavlink#1]
So this 'fastmavlink'  seems to me like its written to be a newer/faster C binding that's got a 'better' api, and is backward compatible with the existing one.... why not just do a PR and integrate it with the existing bindings? . ..... I see no reason we couldn't have two  C bindings, we already have two javascript bindings (i did the new one, as it broke api compatibility  but fixed many things) .You could call your binding FastC or NextGenC  or whatever.

**Comment by olliw42** [comment]
with all due respect, and I do respect you very much, but this is a shockingly naive comment, and out of touch with the reality. I am in many ways an idealistic person, but also rational. I want to make progress, improve things, get things done. The idealistic part made me make the efforts to improve the bindings you mention and contribute, but the reactions had been - well - ... . The rational part made me draw conclusions. You should not only ask me what you think I should do but also ask yourself why someone else should want to do what you think she should do.
Btw, 33% of the currently listed language bindings are not in the repo you mentioned, so this here is not even a precedence.
In addition I conclude that the current architecture with the code generators in a subfolder of a submodule is not good design, to say it politely, hampers progress and is not to the benefit of the community at large, so I would consider merging these bindings to the upstream repo where such bindings IMHO should belong to.
I think I have given a sufficiently detailed answer and thus close the issue. 
I btw think, since this wasn't about an issue with the code base at all, that such things should be better placed and discussed elsewhere, not in issues.

**Comment by davidbuzz** [comment]
Thankyou for taking the time to respond.   Although nothing u said made any technical sense to me, it seems clear to me that non-technically... as an  idealist you tried and failed to do improvements elsewhere, and as a realist, u put them here instead.

**Comment by olliw42** [comment]
of course there is no technical reason it would not be possible ... but that's really a nonsense argument. E.g., there is no technical reason why I could not take my copter and throw it against the wall, yet I would not do it, unless there would be a good argument or reason. You have not yet given any good argument or reason, while I think I have some very good arguments and reasons, which are based on facts and realities. As simple as that. I can't believe what I hear you saying.

**Comment by davidbuzz** [comment]
Hey ollie, if i'm reading the text correctly, u seem to be very upset or angry or frustrated or something..?  I'm just trying to understand, not meaning to cause more upset or anything.

**Comment by olliw42** [comment]
????
I'm nothing of that. Any repo maintainers can run their repo as they want, including the maintainers of the repo you mentioned. I may however have an opinion on how it is run. 
All I want is to make progress, improve things, get things done, and all I do is to try find a path towards that. Paths which do not work out I abandon. I have difficulties to understand why this should be difficult to understand :)
